export const EDITOR_CLASSES = [
  'text-sm text-neutral-300 leading-relaxed',
  '[&_.ProseMirror]:outline-none',
  '[&_.ProseMirror_h1]:text-2xl [&_.ProseMirror_h1]:font-bold [&_.ProseMirror_h1]:text-neutral-100 [&_.ProseMirror_h1]:mt-6 [&_.ProseMirror_h1]:mb-3',
  '[&_.ProseMirror_h2]:text-lg [&_.ProseMirror_h2]:font-semibold [&_.ProseMirror_h2]:text-neutral-100 [&_.ProseMirror_h2]:mt-5 [&_.ProseMirror_h2]:mb-2 [&_.ProseMirror_h2]:border-b [&_.ProseMirror_h2]:border-neutral-800 [&_.ProseMirror_h2]:pb-1',
  '[&_.ProseMirror_h3]:text-base [&_.ProseMirror_h3]:font-semibold [&_.ProseMirror_h3]:text-neutral-200 [&_.ProseMirror_h3]:mt-4 [&_.ProseMirror_h3]:mb-1',
  '[&_.ProseMirror_p]:mb-3 [&_.ProseMirror_p]:text-neutral-300',
  '[&_.ProseMirror_ul]:list-disc [&_.ProseMirror_ul]:pl-5 [&_.ProseMirror_ul]:mb-3',
  '[&_.ProseMirror_ol]:list-decimal [&_.ProseMirror_ol]:pl-5 [&_.ProseMirror_ol]:mb-3',
  '[&_.ProseMirror_li]:mb-1',
  '[&_.ProseMirror_code]:bg-neutral-800 [&_.ProseMirror_code]:px-1 [&_.ProseMirror_code]:rounded [&_.ProseMirror_code]:text-xs [&_.ProseMirror_code]:font-mono [&_.ProseMirror_code]:text-amber-300/90',
  '[&_.ProseMirror_pre]:bg-neutral-900 [&_.ProseMirror_pre]:border [&_.ProseMirror_pre]:border-neutral-800 [&_.ProseMirror_pre]:p-3 [&_.ProseMirror_pre]:rounded [&_.ProseMirror_pre]:mb-3 [&_.ProseMirror_pre]:overflow-x-auto',
  '[&_.ProseMirror_pre_code]:bg-transparent [&_.ProseMirror_pre_code]:p-0 [&_.ProseMirror_pre_code]:text-neutral-300',
  '[&_.ProseMirror_blockquote]:border-l-2 [&_.ProseMirror_blockquote]:border-neutral-600 [&_.ProseMirror_blockquote]:pl-4 [&_.ProseMirror_blockquote]:text-neutral-400 [&_.ProseMirror_blockquote]:mb-3',
  '[&_.ProseMirror_strong]:font-semibold [&_.ProseMirror_strong]:text-neutral-100',
  '[&_.ProseMirror_em]:text-neutral-300',
  '[&_.ProseMirror_hr]:border-neutral-800 [&_.ProseMirror_hr]:my-5',
  '[&_.ProseMirror_table]:w-full [&_.ProseMirror_table]:text-sm [&_.ProseMirror_table]:mb-4 [&_.ProseMirror_table]:border-collapse',
  '[&_.ProseMirror_th]:text-left [&_.ProseMirror_th]:font-semibold [&_.ProseMirror_th]:text-neutral-200 [&_.ProseMirror_th]:border-b [&_.ProseMirror_th]:border-neutral-700 [&_.ProseMirror_th]:pb-2 [&_.ProseMirror_th]:pr-6',
  '[&_.ProseMirror_td]:text-neutral-300 [&_.ProseMirror_td]:border-b [&_.ProseMirror_td]:border-neutral-800/60 [&_.ProseMirror_td]:py-1.5 [&_.ProseMirror_td]:pr-6',
].join(' ')
