/// Regenerate src/bindings.ts from Rust command signatures.
/// Run with: cargo test --test bindings
#[test]
fn export_bindings() {
    beadspec_lib::make_specta_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("// Auto-generated by tauri-specta — do not edit manually.\n// Regenerate: cargo test --test bindings\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}
