// Auto-generated by tauri-specta — do not edit manually.
// Regenerate: cargo test --test bindings

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createTask: (projectPath: string, title: string, description: string | null, priority: number | null, taskType: string | null) => typedError<WriteResult, string>(__TAURI_INVOKE("create_task", { projectPath, title, description, priority, taskType })),
	updateTaskField: (projectPath: string, issueId: string, field: string, value: string) => typedError<WriteResult, string>(__TAURI_INVOKE("update_task_field", { projectPath, issueId, field, value })),
	changeTaskStatus: (projectPath: string, issueId: string, status: string, force: boolean) => typedError<WriteResult, string>(__TAURI_INVOKE("change_task_status", { projectPath, issueId, status, force })),
	addLabel: (projectPath: string, issueId: string, label: string) => typedError<WriteResult, string>(__TAURI_INVOKE("add_label", { projectPath, issueId, label })),
	removeLabel: (projectPath: string, issueId: string, label: string) => typedError<WriteResult, string>(__TAURI_INVOKE("remove_label", { projectPath, issueId, label })),
	addComment: (projectPath: string, issueId: string, body: string) => typedError<WriteResult, string>(__TAURI_INVOKE("add_comment", { projectPath, issueId, body })),
	deleteTask: (projectPath: string, issueId: string) => typedError<WriteResult, string>(__TAURI_INVOKE("delete_task", { projectPath, issueId })),
	linkDependency: (projectPath: string, blockedId: string, blockingId: string) => typedError<WriteResult, string>(__TAURI_INVOKE("link_dependency", { projectPath, blockedId, blockingId })),
	unlinkDependency: (projectPath: string, blockedId: string, blockingId: string) => typedError<WriteResult, string>(__TAURI_INVOKE("unlink_dependency", { projectPath, blockedId, blockingId })),
	connectProject: (projectPath: string) => typedError<ProjectMeta, string>(__TAURI_INVOKE("connect_project", { projectPath })),
	/**
	 *  Drop any half-spawned sidecar registration and re-run `connect_project`.
	 *  Used by the recovery dialog's "Retry" button after a spawn failure: the
	 *  previous attempt may have left a partially-initialised entry that would
	 *  otherwise short-circuit `spawn_or_get`.
	 */
	retryConnectProject: (projectPath: string) => typedError<ProjectMeta, string>(__TAURI_INVOKE("retry_connect_project", { projectPath })),
	disconnectProject: (projectPath: string) => typedError<null, string>(__TAURI_INVOKE("disconnect_project", { projectPath })),
	listProjects: () => typedError<ProjectMeta[], string>(__TAURI_INVOKE("list_projects")),
	listTasks: (projectPath: string, filters: {
	status: string[],
	priority: number[],
	labels: string[],
	search: string | null,
} | null, limit: number | null, afterCursor: string | null, statusFilter: string[] | null, labelFilter: string[] | null, sortCol: string | null, sortDir: string | null) => typedError<TasksResponse, string>(__TAURI_INVOKE("list_tasks", { projectPath, filters, limit, afterCursor, statusFilter, labelFilter, sortCol, sortDir })),
	getTask: (projectPath: string, issueId: string) => typedError<TaskDetail, string>(__TAURI_INVOKE("get_task", { projectPath, issueId })),
	getTaskHistory: (projectPath: string, issueId: string) => typedError<HistoryEntry[], string>(__TAURI_INVOKE("get_task_history", { projectPath, issueId })),
	searchTasks: (projectPath: string, query: string) => typedError<SearchResult[], string>(__TAURI_INVOKE("search_tasks", { projectPath, query })),
	focusMainWindow: () => typedError<null, string>(__TAURI_INVOKE("focus_main_window")),
	/**
	 *  BEADSPEC-4g6 (18.2): Update the tray icon badge with the current open-task count.
	 * 
	 *  The frontend computes the count after each sync and calls this command.
	 *  On macOS the count appears as menu-bar text beside the icon; on other
	 *  platforms it is reflected in the tooltip.
	 */
	updateTrayBadge: (count: number) => typedError<null, string>(__TAURI_INVOKE("update_tray_badge", { count })),
	/**
	 *  BEADSPEC-ghp (18.5): Enable or disable launch-at-login.
	 * 
	 *  Actual OS-level autostart registration requires tauri-plugin-autostart,
	 *  which is not yet in Cargo.toml. This stub stores the intent so the
	 *  frontend preference round-trips correctly; wire up the plugin when added.
	 * 
	 *  TODO: integrate tauri-plugin-autostart when adding it to Cargo.toml.
	 */
	setStartAtLogin: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_start_at_login", { enabled })),
	/**
	 *  BEADSPEC-ghp (18.5): Hide the main window so only the tray icon is visible.
	 * 
	 *  Called by the frontend when the user enables tray-only mode, and
	 *  automatically at startup when `BEADS_TRAY_ONLY` env-var is set.
	 */
	launchToTray: () => typedError<null, string>(__TAURI_INVOKE("launch_to_tray")),
	/**
	 *  Probe health of the dolt server for a given project without side effects.
	 *  Used by the frontend "Try again" button in the recovery modal.
	 */
	probeDoltHealth: (projectPath: string) => typedError<HealthReport, string>(__TAURI_INVOKE("probe_dolt_health", { projectPath })),
	/**
	 *  Attempt to recover a wedged dolt server. If `force = true`, skips
	 *  predicates 3 (no-clients) and 4 (clean working set) but never skips
	 *  ownership or data-dir checks.
	 * 
	 *  On success, the caller should call `connect_project` again.
	 */
	attemptDoltRecovery: (projectPath: string, force: boolean) => typedError<RecoveryResult, string>(__TAURI_INVOKE("attempt_dolt_recovery", { projectPath, force })),
	/**  Run `bd preflight` in the given project. Read op — 10s timeout. */
	bdPreflight: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("bd_preflight", { projectId })),
	/**  Run `bd doctor --json` in the given project. Read op — 10s timeout. */
	bdDoctor: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("bd_doctor", { projectId })),
	/**  Run `bd lint --json` in the given project. Read op — 10s timeout. */
	bdLint: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("bd_lint", { projectId })),
	/**  Run `bd stale --json` in the given project. Read op — 10s timeout. */
	bdStale: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("bd_stale", { projectId })),
	/**  Run `bd orphans --json` in the given project. Read op — 30s timeout. */
	bdOrphans: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("bd_orphans", { projectId })),
	/**  Run `bd formula list --json` in the given project. Read op — 10s timeout. */
	bdFormulaList: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("bd_formula_list", { projectId })),
	/**
	 *  Run `bd mol pour <formula_name>` in the given project. Write op — 30s timeout.
	 * 
	 *  `formula_name` must be a non-empty string containing only alphanumeric
	 *  characters, hyphens, underscores, and dots.  Returns an error if the name
	 *  fails validation so that the backend never constructs a shell-injection path.
	 */
	bdFormulaPour: (projectId: string, formulaName: string) => typedError<string, string>(__TAURI_INVOKE("bd_formula_pour", { projectId, formulaName })),
	/**  Run `bd human list --json` in the given project. Read op — 10s timeout. */
	bdHumanList: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("bd_human_list", { projectId })),
	/**  Run `bd human respond <issue_id> <text>` in the given project. Write op — 30s timeout. */
	bdHumanRespond: (projectId: string, issueId: string, text: string) => typedError<string, string>(__TAURI_INVOKE("bd_human_respond", { projectId, issueId, text })),
	/**  Run `bd human dismiss <issue_id>` in the given project. Write op — 30s timeout. */
	bdHumanDismiss: (projectId: string, issueId: string) => typedError<string, string>(__TAURI_INVOKE("bd_human_dismiss", { projectId, issueId })),
	/**
	 *  Run `ruflo memory search -q <query> --format json`. Read op — 10s timeout.
	 * 
	 *  `query` is passed as a single argument.  Empty queries are rejected.
	 */
	rufloMemorySearch: (query: string) => typedError<string, string>(__TAURI_INVOKE("ruflo_memory_search", { query })),
	/**  Run `ruflo --version` to probe whether ruflo is available. Read op — 10s timeout. */
	rufloVersionProbe: () => typedError<string, string>(__TAURI_INVOKE("ruflo_version_probe")),
	/**
	 *  Derive workspace labels from `git rev-parse --abbrev-ref HEAD` in the
	 *  given project root. Returns unknown/fallback values gracefully if not a
	 *  git repo.
	 */
	getWorkspaceContext: (projectPath: string) => typedError<WorkspaceContext, string>(__TAURI_INVOKE("get_workspace_context", { projectPath })),
	/**  Find git commits and branches that mention a given issue ID. */
	getGitRefsForIssue: (projectPath: string, issueId: string) => typedError<GitRefs, string>(__TAURI_INVOKE("get_git_refs_for_issue", { projectPath, issueId })),
	/**
	 *  Query `dolt_diff('issues', 'HEAD~20', 'HEAD')` filtered to the given
	 *  issue_id. Returns an empty vec on any error (graceful degradation).
	 */
	getDoltHistoryForIssue: (projectPath: string, issueId: string) => typedError<DoltRevision[], string>(__TAURI_INVOKE("get_dolt_history_for_issue", { projectPath, issueId })),
	/**  List all OpenSpec changes (active and archived) for the given project. */
	listChanges: (projectPath: string) => typedError<ChangeInfo[], string>(__TAURI_INVOKE("list_changes", { projectPath })),
	/**
	 *  Read the raw content of a specific artifact file within a change directory.
	 * 
	 *  `artifact` may be a simple filename (`"proposal.md"`) or a nested path
	 *  (`"specs/task-workspace/spec.md"`). Returns an error string if the file
	 *  cannot be read or if the resolved path escapes the change directory.
	 */
	readChangeArtifact: (projectPath: string, change: string, artifact: string) => typedError<string, string>(__TAURI_INVOKE("read_change_artifact", { projectPath, change, artifact })),
	/**  Count done/total checkboxes in a change's `tasks.md`. */
	getChangeProgress: (projectPath: string, change: string) => typedError<ChangeProgress, string>(__TAURI_INVOKE("get_change_progress", { projectPath, change })),
	/**
	 *  Count Beads issues tagged `openspec:<slug>` for this change, regardless of
	 *  any UI-level status filter. Returns `done` (closed non-feature/non-epic
	 *  tasks), `total` (all non-feature/non-epic tasks), and `epic_id` (the single
	 *  feature/epic-typed issue, if present).
	 */
	getChangeBeadsProgress: (projectPath: string, changeSlug: string) => typedError<ChangeBeadsProgress, string>(__TAURI_INVOKE("get_change_beads_progress", { projectPath, changeSlug })),
	/**
	 *  Inter-change dependency lookup for a change. Resolves the change's imported
	 *  epic, then queries the Beads `dependencies` table for direct upstream
	 *  (blockers) and downstream (dependents) epics carrying any `openspec:*`
	 *  label. Non-OpenSpec dependencies and self-loops are filtered out.
	 */
	getChangeDependencies: (projectPath: string, changeSlug: string) => typedError<ChangeDependencies, string>(__TAURI_INVOKE("get_change_dependencies", { projectPath, changeSlug })),
	/**  Run `openspec validate <change>` via the `ruflo` CLI and parse the output. */
	runOpenspecValidate: (projectPath: string, change: string) => typedError<ValidationResult, string>(__TAURI_INVOKE("run_openspec_validate", { projectPath, change })),
	/**  Shell out to `openspec-beads-import <change>` to import a change into Beads. */
	importChangeToBeads: (projectPath: string, change: string) => typedError<CommandOutput, string>(__TAURI_INVOKE("import_change_to_beads", { projectPath, change })),
	/**  Manually trigger `tasks.md` checkbox reconciliation for all active OpenSpec changes. */
	reconcileOpenspecCheckboxes: (projectPath: string) => typedError<SyncReport, string>(__TAURI_INVOKE("reconcile_openspec_checkboxes", { projectPath })),
	/**  Return the current quick-capture shortcut and whether it's available. */
	getShortcutStatus: () => __TAURI_INVOKE<ShortcutStatus>("get_shortcut_status"),
	/**
	 *  Section 6.1: Unregister the old quick-capture shortcut and register a new one.
	 * 
	 *  Returns `Err` if the new shortcut string is invalid or conflicts with another app.
	 *  On success, updates `AppState` with the new shortcut string.
	 */
	registerQuickCaptureShortcut: (shortcut: string) => typedError<null, string>(__TAURI_INVOKE("register_quick_capture_shortcut", { shortcut })),
	/**
	 *  Tauri command: validate a custom binary path before the frontend persists it.
	 * 
	 *  Checks that the path exists and has the executable bit set (Unix).  The
	 *  frontend should call this whenever the user changes any binary path in
	 *  Settings and display the returned error string if `Err` is returned.
	 */
	validateBinaryPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("validate_binary_path", { path })),
};

/* Types */
/**
 *  Beads-import progress for a change. Counts non-feature/non-epic Beads
 *  issues carrying the `openspec:<slug>` label across **all** statuses
 *  (except `deleted`), so the OpenSpec card stays accurate even when the UI's
 *  status filter would hide some of them.
 */
export type ChangeBeadsProgress = {
	done: number,
	total: number,
	/**  ID of the imported epic/feature for this change, if one exists. */
	epic_id: string | null,
};

/**
 *  One end of an inter-change dependency edge, identified by the related
 *  change's slug and the Beads epic ID that backs it.
 */
export type ChangeDepLink = {
	slug: string,
	epic_id: string,
};

/**
 *  Upstream and downstream inter-change dependency lists for a single change.
 *  `upstream` = changes this one is blocked by; `downstream` = changes that
 *  depend on this one.
 */
export type ChangeDependencies = {
	upstream: ChangeDepLink[],
	downstream: ChangeDepLink[],
};

/**  Metadata for a single OpenSpec change directory. */
export type ChangeInfo = {
	name: string,
	/**
	 *  Canonical slug used for beads label matching (`openspec:<slug>`).
	 *  For archived changes the leading `YYYY-MM-DD-` date prefix is stripped.
	 */
	slug: string,
	is_archived: boolean,
	has_proposal: boolean,
	has_design: boolean,
	has_tasks: boolean,
	last_modified: string | null,
	specs: string[],
};

/**  Task-completion progress derived from a `tasks.md` file. */
export type ChangeProgress = {
	done: number,
	total: number,
};

/**  Generic output from a shelled-out CLI command. */
export type CommandOutput = {
	stdout: string,
	stderr: string,
	exit_code: number,
};

/**  A single git commit reference associated with an issue. */
export type CommitRef = {
	hash: string,
	subject: string,
	date: string,
};

/**  Classification of a dolt SQL server's health at startup probe time. */
export type DoltHealth = { kind: "ok" } | { kind: "port_bound_but_not_responding"; pid: number | null } | { kind: "port_unbound_but_orphan_running"; pid: number; port: number; data_dir: string } | { kind: "not_running" } | { kind: "foreign_process_holding_port"; pid: number; exe: string } | { kind: "spawn_failed"; attempts: number; last_error: string; stderr_tail: string };

/**  A single row from `dolt_diff` for the issues table. */
export type DoltRevision = {
	diff_type: string,
	from_id: string | null,
	to_id: string | null,
	from_title: string | null,
	to_title: string | null,
	from_status: string | null,
	to_status: string | null,
};

/**  Git refs (commits + branches) that mention a given issue ID. */
export type GitRefs = {
	commits: CommitRef[],
	branches: string[],
};

/**  Full diagnostic report returned to the frontend on project open. */
export type HealthReport = {
	health: DoltHealth,
	project_path: string,
	configured_port: number,
	orphans: OrphanInfo[],
};

export type HistoryEntry = {
	id: string,
	field: string,
	old_value: string | null,
	new_value: string | null,
	actor: string,
	timestamp: string,
	entry_type: string,
	body: string | null,
};

/**  A dolt sql-server process that is running but should not be. */
export type OrphanInfo = {
	pid: number,
	port: number | null,
	data_dir: string,
	safety: SafetyDecision,
};

export type ProjectMeta = {
	/**  Canonical filesystem path to the project root (user-displayable). */
	project_path: string,
	/**
	 *  Opaque identifier derived from the canonical project path (hex-encoded
	 *  first 8 bytes of SHA-256). Never contains connection secrets.
	 */
	project_id: string,
	name: string,
	prefix: string,
	compatible: boolean,
	schema_message: string,
};

/**  Result of an attempted recovery operation. */
export type RecoveryResult = { outcome: "success"; port: number } | { outcome: "still_unsafe"; reason: string } | { outcome: "error"; message: string };

/**  Whether it is safe to automatically kill an orphan. */
export type SafetyDecision = { decision: "allowed" } | { decision: "escalate"; reason: string };

export type SearchResult = {
	id: string,
	title: string,
	status: string,
	score: number,
};

/**  Status of the quick-capture shortcut — exposed to the frontend. */
export type ShortcutStatus = {
	shortcut: string,
	available: boolean,
};

/**  Report returned by `reconcile_openspec_checkboxes`. */
export type SyncReport = {
	changes_scanned: number,
	lines_flipped: number,
	lines_already_correct: number,
	issues_unmatched: number,
	errors: string[],
};

export type Task = {
	id: string,
	title: string,
	status: string,
	priority: number,
	task_type: string,
	assignee: string | null,
	labels: string[],
	created_at: string,
	updated_at: string,
};

export type TaskDetail = {
	id: string,
	title: string,
	status: string,
	priority: number,
	task_type: string,
	assignee: string | null,
	description: string | null,
	labels: string[],
	dependencies: string[],
	dependents: string[],
	created_at: string,
	updated_at: string,
};

export type TaskFilters = {
	status: string[],
	priority: number[],
	labels: string[],
	search: string | null,
};

export type TasksResponse = {
	tasks: Task[],
	/**  Total number of matching tasks (without pagination). Capped at u32::MAX in practice. */
	total_count: number,
	next_cursor: string | null,
};

/**  Result from running `openspec validate` against a change. */
export type ValidationResult = {
	valid: boolean,
	errors: string[],
};

/**  Workspace context derived from git for the connected project. */
export type WorkspaceContext = {
	branch: string,
	label_branch: string,
	label_worktree: string,
	label_repo: string,
};

/**
 *  Returned by write commands. The frontend uses this to track pending mutations
 *  and roll back the optimistic update if the command fails.
 */
export type WriteResult = {
	optimistic_id: string,
	output: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

